spring.application.name=ModernEmployeeTracker


# =============================================
# DATABASE CONFIGURATION
# =============================================
spring.datasource.url=jdbc:mysql://localhost:3306/employee_tracker?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.mvc.format.date=yyyy-MM-dd
# =============================================
# JPA / HIBERNATE
# =============================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# =============================================
# JSP VIEW RESOLVER
# =============================================
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp



# Static resources path


spring.mvc.static-path-pattern=/**
spring.web.resources.static-locations=classpath:/static/
# =============================================
# PAGINATION DEFAULT
# =============================================
app.pagination.page-size=8
